github:
  is_project_page: false

plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true

theme: jekyll-theme-cayman

title: [Scrum Guides Community Translations]
description: [Together we create our community editions to share the knowledge.]
show_downloads: false
google_analytics: UA-177167416-1
