github:
  is_project_page: false

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled:     true

theme: jekyll-theme-cayman

title: [Scrum Guides Community Translations]
description: [Together we create our community editions to share the knowledge.]
show_downloads: false
google_analytics: UA-177167416-1

facebook:
  app_id: 734176127193250
twitter:
  username: ToastedIceCream
  card: summary
